services:
    minio:
        restart: always
        image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server /data --console-address ':9001' --address ':9000'
        environment:
            - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
            - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
        volumes:
            - minio_data:/data

    mc:
        image: minio/mc:RELEASE.2025-08-13T08-35-41Z-cpuv1
        depends_on:
            - minio
        container_name: mc
        env_file:
            - .env
        entrypoint: >
            /bin/sh -c "
            /tmp/wait-for-it.sh minio:9000 &&
            /usr/bin/mc alias set minio http://minio:9000 ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} &&
            /usr/bin/mc mb minio/${MLFLOW_S3_BUCKET};
            /usr/bin/mc mb minio/${DVC_BUCKET};
            exit 0;
            "
        volumes:
            - ./docker/wait-for-it.sh:/tmp/wait-for-it.sh:ro
volumes:
    minio_data: