
services:
  app:
    build:
      network: host
      context: .
      dockerfile: docker/Dockerfile.mlflow_api
    container_name: mlflow_api
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MLFLOWAPI_API_KEY=${MLFLOWAPI_API_KEY}
      - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
      - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}
    expose:
      - "8000"
    restart: always
    entrypoint: /bin/bash
    command:
      - -c
      - |
        /tmp/wait-for-it.sh $(echo ${MLFLOW_S3_ENDPOINT_URL} | sed -E 's~https?://~~') -t 60 --
        /tmp/wait-for-it.sh $(echo ${MLFLOW_TRACKING_URI} | sed -E 's~https?://~~') -t 60 --
        gunicorn app:app -w 4 -b 0.0.0.0:8000
  nginx_mlflowapi:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8000:8000"
    volumes:
      - ./etc/mlflow_api/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: always
