FROM tensorflow/tensorflow:2.20.0

RUN pip install --upgrade pip

COPY ../deps/requirements_tensorboard.txt /tmp/requirements_tensorboard.txt

RUN pip install --no-cache-dir -r /tmp/requirements_tensorboard.txt

RUN apt-get update && apt-get install -y apache2-utils && rm -rf /var/lib/apt/lists/*