FROM apache/airflow:3.1.0

USER root

RUN apt-get update && \
    apt-get install -y git && \
    rm -rf /var/lib/apt/lists/*

USER airflow

COPY ../deps/requirements_airflow.txt .

RUN pip install --no-cache-dir  -r requirements_airflow.txt

